name: 'Terraform PR Validation'

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-validation:
    name: 'Terraform PR Validation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1 # Or your desired region

      # The terraform plan step is not being run here because pull requests from forked
      # repositories do not have access to secrets. This is a security measure by GitHub.
      # The plan step would require AWS credentials, which are stored as secrets.
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
